### ISSUE TITLE
Columns must be same length as key

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/sr-detection#183]
```text
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/sr-detection/sr-detection/sr-data/src/sr_data/steps/gh_mentions.py", line 36, in main
    frame[["readme_pmentions", "readme_imentions"]] = (
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/sr-data-iIS7NBSl-py3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "/home/runner/.cache/pypoetry/virtualenvs/sr-data-iIS7NBSl-py3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "/home/runner/.cache/pypoetry/virtualenvs/sr-data-iIS7NBSl-py3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
error: Recipe `ghmentions` failed on line 122 with exit code 1
cp: cannot stat 'after-ghmentions.csv': No such file or directory
Error: Process completed with exit code 1.
```

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.13`, title is `0.0.13`
