### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/sr-detection#189]
from [here](https://github.com/h1alexbel/sr-detection/actions/runs/11618919716/job/32357615388):

```text
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/sr-detection/sr-detection/sr-data/src/sr_data/steps/extract.py", line 46, in main
    frame["readme_hcount"] = frame["headings"].apply(readme_hcount)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/sr-data-iIS7NBSl-py3.12/lib/python3.12/site-packages/pandas/core/series.py", line 4924, in apply
    ).apply()
      ^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/sr-data-iIS7NBSl-py3.12/lib/python3.12/site-packages/pandas/core/apply.py", line 1427, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/sr-data-iIS7NBSl-py3.12/lib/python3.12/site-packages/pandas/core/apply.py", line 1507, in apply_standard
    mapped = obj._map_values(
             ^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/sr-data-iIS7NBSl-py3.12/lib/python3.12/site-packages/pandas/core/base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/sr-data-iIS7NBSl-py3.12/lib/python3.12/site-packages/pandas/core/algorithms.py", line 1743, in map_array
    return lib.map_infer(values, mapper, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2972, in pandas._libs.lib.map_infer
  File "/home/runner/work/sr-detection/sr-detection/sr-data/src/sr_data/steps/extract.py", line 72, in readme_hcount
    return len(headings)
           ^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.16`
