### ISSUE TITLE
Can't parse workflows for `BillyDM/vitalium-verb`

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/sr-detection#259]
Getting this:

```text
2024-11-29 17:26:40.017 | INFO     | sr_data.steps.workflows:main:46 - Repo BillyDM/vitalium-verb has 1 *.yml|*.yaml workflows inside .github/workflows
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/sr-data/src/sr_data/steps/workflows.py", line 50, in main
    workflow_info(
  File "/sr-data/src/sr_data/steps/workflows.py", line 88, in workflow_info
    for matrixed in jdetails.get("strategy").get("matrix").get(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
error: Recipe `workflows` failed on line 140 with exit code 1
```

Full logs are [here](https://github.com/h1alexbel/sr-detection/actions/runs/12088651354/job/33712557827)

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.23`
