### ISSUE TITLE
Can't parse `polespinasa/bitcoin-grouphug`

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/sr-detection#261]
Getting this:

```text
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/sr-data/src/sr_data/steps/workflows.py", line 50, in main
    workflow_info(
  File "/sr-data/src/sr_data/steps/workflows.py", line 113, in workflow_info
    "w_release": used_for_releases(yml)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/sr-data/src/sr_data/steps/workflows.py", line 121, in used_for_releases
    if on.get("release"):
       ^^^^^^
```

full logs are [here](https://github.com/h1alexbel/sr-detection/actions/runs/12118257312/job/33782380303)

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.24`
