### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/sr-detection#264]
This one fails:

```yml
on: [push, pull_request]
```

```text
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/sr-data/src/sr_data/steps/workflows.py", line 50, in main
    workflow_info(
  File "/sr-data/src/sr_data/steps/workflows.py", line 113, in workflow_info
    "w_release": used_for_releases(yml)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/sr-data/src/sr_data/steps/workflows.py", line 121, in used_for_releases
    if on.get("release"):
       ^^^^^^
AttributeError: 'list' object has no attribute 'get'
```

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.25`
