### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/sr-detection#266]
Getting this:

```text
2024-12-03 08:02:32.108 | INFO     | sr_data.steps.workflows:main:46 - Repo rohaquinlop/complexipy has 1 *.yml|*.yaml workflows inside .github/workflows
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/sr-data/src/sr_data/steps/workflows.py", line 50, in main
    workflow_info(
  File "/sr-data/src/sr_data/steps/workflows.py", line 108, in workflow_info
    oss = set(oss)
          ^^^^^^^^
TypeError: unhashable type: 'dict'
```

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.26`
