### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/sr-detection#271]
Getting this:

```text
2024-12-03 13:22:27.892 | INFO     | sr_data.steps.workflows:main:46 - Repo LyonSyonII/run has 1 *.yml|*.yaml workflows inside .github/workflows
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/sr-data/src/sr_data/steps/workflows.py", line 50, in main
    workflow_info(
  File "/sr-data/src/sr_data/steps/workflows.py", line 96, in workflow_info
    if matrix.get(keys[0]):
       ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.28`
