### ISSUE TITLE
AttributeError: 'list' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/sr-detection#276]
Getting this:

```text
2024-12-04 07:11:53.107 | INFO     | sr_data.steps.workflows:main:46 - Repo fineshopdesign/cf-wasm has 5 *.yml|*.yaml workflows inside .github/workflows
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/sr-data/src/sr_data/steps/workflows.py", line 50, in main
    workflow_info(
  File "/sr-data/src/sr_data/steps/workflows.py", line 89, in workflow_info
    if runs.startswith("$"):
       ^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'startswith'
```

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.29`
