### ISSUE TITLE
Unsupported dtype object in `has_release_workflow`

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/sr-detection#279]
Getting this after running clustering:

```text
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/aliaksei/code/research/sr-detection/sr-train/src/models/cluster.py", line 155, in main
    cmeans(dataset, f"{dir}/cmeans")
  File "/Users/aliaksei/code/research/sr-detection/sr-train/src/models/cluster.py", line 104, in cmeans
    centroids, u, u0, d, jm, p, fpc = skfuzzy.cmeans(
                                      ^^^^^^^^^^^^^^^
  File "/Users/aliaksei/Library/Caches/pypoetry/virtualenvs/sr-train-7xxrtfq2-py3.12/lib/python3.12/site-packages/skfuzzy/cluster/_cmeans.py", line 173, in cmeans
    [cntr, u, Jjm, d] = _cmeans0(data, u2, c, m, metric)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aliaksei/Library/Caches/pypoetry/virtualenvs/sr-train-7xxrtfq2-py3.12/lib/python3.12/site-packages/skfuzzy/cluster/_cmeans.py", line 29, in _cmeans0
    d = _distance(data, cntr, metric)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aliaksei/Library/Caches/pypoetry/virtualenvs/sr-train-7xxrtfq2-py3.12/lib/python3.12/site-packages/skfuzzy/cluster/_cmeans.py", line 61, in _distance
    return cdist(data, centers, metric=metric).T
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aliaksei/Library/Caches/pypoetry/virtualenvs/sr-train-7xxrtfq2-py3.12/lib/python3.12/site-packages/scipy/spatial/distance.py", line 2980, in cdist
    return cdist_fn(XA, XB, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unsupported dtype object
error: Recipe `cluster` failed on line 201 with exit code 1
```

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.31`
